extends: ['../.eslintrc.yml', 'next']
rules:
  '@next/next/no-html-link-for-pages': off # using app router, so no pages dir to check
overrides:
  - files: ['src/components/Counter.tsx']
    rules:
      '@typescript-eslint/no-misused-promises': off
